name: tests

on:
  push:
    paths-ignore:
      - "**.md"
  pull_request:
    types: [opened, synchronize, reopened, edited]
    paths-ignore:
      - "**.md"

jobs:
  tests:
    name: Test
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            python_version: "3.8"
          - os: ubuntu-latest
            python_version: "3.9"
          - os: macos-latest
            python_version: "3.10"
          - os: ubuntu-latest
            python_version: "3.11"

    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Configure Python version
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python_version }}
          architecture: x64

      - name: Install/upgrade build tools
        run: |
          python -m pip install -U build pip setuptools wheel

      - name: Install torch
        run: |
          python -m pip install torch --index-url https://download.pytorch.org/whl/cpu

      - name: Install dependencies
        run: |
          python -m pip install -r requirements.txt

      - name: Build sdist
        run: |
          python -m build --sdist

      - name: Run mypy
        run: python -m mypy spacy_transformers_pipeline

      - name: Delete source directory
        run: rm -rf spacy_transformers_pipeline
        shell: bash

      - name: Uninstall all packages
        run: |
          python -m pip freeze --exclude pywin32 --exclude torch
          python -m pip freeze --exclude pywin32 --exclude torch > installed.txt
          python -m pip uninstall -y -r installed.txt

      - name: Install from sdist
        run: |
          SDIST=$(python -c "import os;print(os.listdir('./dist')[-1])" 2>&1)
          python -m pip install dist/$SDIST
        shell: bash

      - name: Run tests
        run: |
          python -m pip install -r requirements.txt
          python -m pytest --pyargs spacy_transformers_pipeline
